include:
  - local: templates/Terraform.gitlab-ci.yml
  - local: templates/AWS-OIDC.gitlab-ci.yml

image:
  name: "sebaczech/gitlab-runner-terraform-aws-cli:1.0"

stages:
  - validate
  - test
  - build
  - deploy

fmt:
  extends: .terraform:fmt
  needs: []

validate:
  extends: .terraform:validate
  needs: []

build:
  extends: .terraform:build

deploy:
  extends: .terraform:deploy
  dependencies:
    - build
  environment:
    name: $TF_STATE_NAME
