include:
  - local: templates/Terraform.gitlab-ci.yml
  - local: templates/AWS-OIDC.gitlab-ci.yml

image:
  name: "sebaczech/gitlab-runner-terraform-aws-cli:1.0"

stages:
  - validate
  - test
  - build
  - deploy
  - cleanup
