include:
  - local: pipeline/Terraform.gitlab-ci.yml
  - local: pipeline/AWS-OIDC.gitlab-ci.yml

image:
  name: "sebaczech/gitlab-runner-terraform-aws-cli:1.0"

stages:
  - check
  - test
  - build
  - deploy
  - cleanup
