variables:
  TF_ROOT: ${CI_PROJECT_DIR}
  TF_STATE_NAME: ${TF_STATE_NAME:terraform.tfstate}

cache:
  key: "${TF_ROOT}"
  paths:
    - ${TF_ROOT}

fmt:
  stage: check
  script:
    - cd "${TF_ROOT}"
    - terraform fmt
  allow_failure: true

validate:
  stage: test
  script:
    - cd "${TF_ROOT}"
    - terraform init
    - terraform validate

plan:
  stage: build
  script:
    - cd "${TF_ROOT}"
    - . auth_aws.sh
    - terraform plan -out=plan
  resource_group: ${TF_STATE_NAME}
  artifacts:
    paths:
      - ${TF_ROOT}/plan
    reports:
      terraform: ${TF_ROOT}/plan.json

apply:
  stage: deploy
  script:
    - cd "${TF_ROOT}"
    - . auth_aws.sh
    - terraform apply
  resource_group: ${TF_STATE_NAME}
  environment: production
  dependencies:
    - plan

destroy:
  stage: cleanup
  script:
    - cd "${TF_ROOT}"
    - . auth_aws.sh
    - terraform destroy
  resource_group: ${TF_STATE_NAME}
  environment: production
  dependencies:
    - plan
    - apply
