variables:
  TF_ROOT: ${CI_PROJECT_DIR}
  TF_STATE_NAME: ${TF_STATE_NAME:terraform.tfstate}

cache:
  key: "${TF_ROOT}"
  paths:
    - ${TF_ROOT}

fmt:
  stage: validate
  script:
    - cd "${TF_ROOT}"
    - terraform fmt
  allow_failure: true

validate:
  stage: validate
  script:
    - cd "${TF_ROOT}"
    - terraform init
    - terraform validate

plan:
  stage: build
  script:
    - cd "${TF_ROOT}"
    - terraform plan
    - terraform plan-json
  resource_group: ${TF_STATE_NAME}
  artifacts:
    paths:
      - ${TF_ROOT}/plan.cache
    reports:
      terraform: ${TF_ROOT}/plan.json

apply:
  stage: deploy
  script:
    - cd "${TF_ROOT}"
    - terraform apply
  resource_group: ${TF_STATE_NAME}
  environment: production

destroy:
  stage: cleanup
  script:
    - cd "${TF_ROOT}"
    - terraform destroy
  resource_group: ${TF_STATE_NAME}
  environment: production
